### PR TITLE
Build theme

### PR DESCRIPTION
**Pull request by ptz0n**
This exposes a `build` method to replace partial tags `{{>partial_file}}` with the content of the each file.

### CODE REVIEW

**Comment by vincentorback** [comment]
:+1:

**Comment by kalasjocke** [comment]
:+1:

**Comment by smartmike** [comment]
:+1:

Is this PR likely to be merged, or has development kinda stopped on this repo?

**Comment by ScottSavarie** [comment]
Also curious!

**Comment by sebastianekstrom** [comment]
LGTM

**Pull request merged**
